#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# =======
# IMPORTS
# =======
source "${SCRIPT_DIR}/../helpers/log_formatting.sh"
source "${SCRIPT_DIR}/../helpers/system_common.sh"


# =============================================================================
#  PREVIEW FUNCTIONS
# =============================================================================
show_context() {

    echo ""
    echo -e "${BOLD}${CYAN}══════════════════════════════════════════${RESET}"
    echo -e "${BOLD}${CYAN}  Network Setup Configuration${RESET}"
    echo -e "${BOLD}${CYAN}══════════════════════════════════════════${RESET}"
    echo ""
    section "General"
    echo -e "  ${GREEN}${BOLD}Current User: ${RESET} ${CURRENT_USER}"
    echo -e "  ${GREEN}${BOLD}Robot Name: ${RESET} ${ROBOT_NAME}"
    echo ""

    section "Network"
    echo -e "  ${GREEN}${BOLD}rmem_max: ${RESET} ${RMEM_MAX}"
    echo -e "  ${GREEN}${BOLD}rmem_default: ${RESET} ${RMEM_DEFAULT}"
    echo -e "  ${GREEN}${BOLD}wmem_max: ${RESET} ${WMEM_MAX}"
    echo -e "  ${GREEN}${BOLD}wmem_default: ${RESET} ${WMEM_DEFAULT}"
    echo ""
    echo -e "  ${GREEN}${BOLD}SYSCTL Directory: ${RESET} ${SYSCTL_CONF_DIR}"
    echo -e "  ${GREEN}${BOLD}SYSCTL Config File: ${RESET} ${SYSCTL_CONF_FILE}"
    echo -e "  ${GREEN}${BOLD}RC_LOCAL: ${RESET} ${RC_LOCAL}"
    echo ""

    confirm_or_skip "Proceed with these values?"

    return 0
}

# =============================================================================
#  NETWORK FUNCTIONS
# =============================================================================
install_sysctl_conf() {
    info "Writing sysctl config: ${SYSCTL_CONF_FILE}"

    cat > "${SYSCTL_CONF_FILE}" << EOF
# =============================================================================
#  Micipsa ROS 2 / CycloneDDS network buffer tuning
#  Generated by install_network.sh
# =============================================================================
net.core.rmem_max=${RMEM_MAX}
net.core.rmem_default=${RMEM_DEFAULT}
net.core.wmem_max=${WMEM_MAX}
net.core.wmem_default=${WMEM_DEFAULT}
EOF

    success "Written: ${SYSCTL_CONF_FILE}"

    info "Applying sysctl values immediately..."
    sysctl -p "${SYSCTL_CONF_FILE}"
    success "Values applied"
}


install_rc_local() {
    info "aarch64 platform detected, installing rc.local"

    if [[ -f "${RC_LOCAL}" ]]; then
        info "Overwriting existing ${RC_LOCAL}"
    else
        info "Creating ${RC_LOCAL}"
    fi

    cat > "${RC_LOCAL}" << EOF
#!/bin/sh -e

# --- Micipsa: ROS 2 / CycloneDDS network buffer tuning ---
/sbin/sysctl -w net.core.rmem_max=${RMEM_MAX}
/sbin/sysctl -w net.core.rmem_default=${RMEM_DEFAULT}
/sbin/sysctl -w net.core.wmem_max=${WMEM_MAX}
/sbin/sysctl -w net.core.wmem_default=${WMEM_DEFAULT}
# --- end Micipsa block ---

exit 0
EOF

    chmod +x "${RC_LOCAL}"
    success "Written and made executable: ${RC_LOCAL}"
}

install_network_config() {
    install_sysctl_conf

    if [[ "${PLATFORM}" == "aarch64" ]]; then
        install_rc_local
    fi
}


# =============================================================================
#  MAIN
# =============================================================================
main() {
    require_root
    setup_error_traps

    PLATFORM="$(detect_platform)"

    robot_system_config_load
    show_context

    install_network_config

    exit "${EXIT_SUCCESS}"
}

main "$@"